
<script src="{{URL::asset('js/jquery.min.js')}}"></script>
<script src="{{URL::asset('js/jquery-migrate-3.0.1.min.js')}}"></script>
<script src="{{URL::asset('js/boostrap-bundle-min.js')}}"></script>
<script src="{{URL::asset('js/popper.min.js')}}"></script>
<script src="{{URL::asset('js/bootstrap.min.js')}}"></script>
<script src="{{URL::asset('js/jquery.easing.1.3.js')}}"></script>
<script src="{{URL::asset('js/jquery.waypoints.min.js')}}"></script>
<script src="{{URL::asset('js/jquery.stellar.min.js')}}"></script>
<script src="{{URL::asset('js/owl.carousel.min.js')}}"></script>
<script src="{{URL::asset('js/jquery.magnific-popup.min.js')}}"></script>
<script src="{{URL::asset('js/aos.js')}}"></script>
<script src="{{URL::asset('js/jquery.animateNumber.min.js')}}"></script>
<script src="{{URL::asset('js/bootstrap-datepicker.js')}}"></script>
<script src="{{URL::asset('js/jquery.timepicker.min.js')}}"></script>
<script src="{{URL::asset('js/scrollax.min.js')}}"></script>
<script src="{{URL::asset('https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false')}}"></script>
<script src="{{URL::asset('js/google-map.js')}}"></script>
<script src="{{URL::asset('js/main.js')}}"></script>
<script src="{{URL::asset('js/sweetalert2.all.min.js')}}"></script>
<script src="{{URL::asset('assets/vendor/jquery/jquery.min.js')}}"></script>
<script src="{{URL::asset('assets/vendor/bootstrap/js/bootstrap.min.js')}}"></script>
<script src="{{URL::asset('assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js')}}"></script>
<script src="{{URL::asset('assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js')}}"></script>
<script src="{{URL::asset('assets/vendor/chartist/js/chartist.min.js')}}"></script>
<script src="{{URL::asset('assets/scripts/klorofil-common.js')}}"></script></script>
